### ISSUE TITLE
 failed to flush to Redis Cluster

### ISSUE THREAD

**Issue by fabregas4you** [fluent-plugins-nursery/fluent-plugin-redis#25]
#### Problem
SetUP Redis Cluster and try to use same as "Stand-Alone redis server", but  failed to flush. 

#### Steps to replicate
- td-agent.log 
```
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/redis-3.3.5/lib/redis.rb:2254:in `pipelined'
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-redis-0.3.3/lib/fluent/plugin/out_redis.rb:78:in `write'
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-02-28 07:07:40 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-02-28 07:07:41 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-28 07:07:41 +0000 chunk="566404c81a32ba03e1eed843ab440078" error_class=Redis::CommandError error="MOVED 14935 127.0.0.1:7000"
```

#### Expected Behavior
- Use like "redis-cli -c" if I could. 

#### Your environment

* OS version 
  * Linux 2.6.32-696.20.1.el6.x86_64 , CentOS-6.9
* paste result of ``fluentd --version`` or ``td-agent --version``
 * fluentd 1.0.2
 * td-agent-3.1.1-0.el6.x86_64
* plugin version
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
  * gem list 
  ```
  $ td-agent-gem list
  *** LOCAL GEMS ***
  bigdecimal (default: 1.3.0)
  bundler (1.16.0)
  cool.io (1.5.3)
  fluent-logger (0.7.1)
  fluent-plugin-bigquery (1.2.0)
  fluent-plugin-elasticsearch (2.4.0)
  fluent-plugin-kafka (0.6.5)
  fluent-plugin-redis (0.3.3)
  fluent-plugin-rewrite-tag-filter (2.0.1)
  fluent-plugin-s3 (1.1.0)
  fluent-plugin-td (1.0.0)
  fluent-plugin-td-monitoring (0.2.3)
  fluent-plugin-webhdfs (1.2.2)
  fluentd (1.0.2)
  json (default: 2.0.4)
  jwt (2.1.0)
  little-plugger (1.1.4)
  logging (2.2.2)
  ltsv (0.1.0)
  msgpack (1.2.0)
  multi_json (1.12.2) 
  multipart-post (2.0.0)
  nokogiri (1.8.1)
  ohai (6.20.0)
  oj (3.3.9)
  openssl (default: 2.0.5) 
  os (0.9.6)
  parallel (1.12.1)
  power_assert (0.4.1)
  psych (default: 2.2.2) 
  public_suffix (3.0.1)
  rake (12.0.0)
  rdoc (default: 5.0.0)
  redis (3.3.5)
  serverengine (2.0.5)
  sigdump (0.2.4)
  signet (0.8.1)
  td (0.15.7)
  td-client (1.0.4)
  td-logger (0.3.27)
  test-unit (3.2.3)
  thread_safe (0.3.6)
  tzinfo (1.2.4)
  tzinfo-data (1.2017.3)
  uber (0.1.0)
  webhdfs (0.8.0)
  xmlrpc (0.2.1)
  yajl-ruby (1.3.1)
  zip-zip (0.3)
  ```

**Comment by cosmo0920** [comment]
This is expected behavior.
Currently, Redis Cluster does not support.
ref: https://github.com/redis/redis-rb/pull/716

**Comment by fabregas4you** [comment]
Oh..., I got it.
Thank you for your quick reply.
